ShopOnlineApp/ShopOnline.WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ShopOnline.BAL;
using ShopOnline.UI.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ShopOnline.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IOrderManager _orderManager;
        public HomeController(ILogger<HomeController> logger, IOrderManager orderManager)
        {
            _logger = logger;
            _orderManager = orderManager;
        }

        public IActionResult Index()
        {
            return View(_orderManager.Orders);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShopOnlineApp/ShopOnline.WebApp/Controllers/ProductCatalogController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using ShopOnline.BAL;
using ShopOnline.Model;
using ShopOnline.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopOnline.UI.Controllers
{
    public class ProductCatalogController : Controller
    {
        private readonly IProductCatalogManager _pdMgr;
        private readonly ICartManager _cartMgr;
        private readonly IOptions<ProductCatalogServiceOption> _options;
        public ProductCatalogController(IProductCatalogManager pdMgr,ICartManager cartManager
            ,IOptions<ProductCatalogServiceOption> pcServiceOption)
        {

            _pdMgr = pdMgr;
            _cartMgr = cartManager;
            _options = pcServiceOption;
        }

        // GET: All Products
        public async Task<ActionResult> Index()
        {
            _pdMgr.Url = _options.Value.BaseUrl + _options.Value.GetAllProduct;
            var products = await _pdMgr.GetProducts();
            return View(products);
        }

        // GET: Product/Details/5
        public async Task<ActionResult> Detail(string id)
        {
            _pdMgr.Url = _options.Value.BaseUrl + string.Format(_options.Value.GetProductDetail,id);
            var product = await _pdMgr.ProductDetail();
            return View(product);
        }

        // GET: Add product for order
        [HttpPost]
        public async Task AddToOrder([FromBody] string productId)
        {
            _pdMgr.Url = _options.Value.BaseUrl + _options.Value.GetAllProduct;
            var prodCollection = await _pdMgr.GetProducts();
            var prod = prodCollection.FirstOrDefault(p => p.ProductId == productId);
            _cartMgr.CartProduct.Add(prod);
        }

        // Check Out
        public ActionResult CheckOut()
        {
            return RedirectToAction("Index", "Cart");
        }
    }
}

ShopOnlineApp/ShopOnline.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Past Orders";
}
@model IEnumerable<Order>

<h1>Past Orders</h1>
@if (Model != null)
{
    <table class="table table-primary table-responsive-lg table-hover">
        <thead>
            <tr>
                <th>ORN</th>
                <th>Order Id</th>
                <th>Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <td>@m.OrderReferenceNumber</td>
                    <td>@m.OrderId</td>
                    <td>Rs. @m.NetPrice</td>
                    <td>
                        @if (m.Status == "PaymentPending")
                        {
                            <span>Payment in progress</span>
                        }
                        else if (m.Status == "OrderAccepted")
                        {
                            <span>Accepted</span>
                        }
                        else if (m.Status == "InTransit")
                        {
                            <span>InTransit</span>
                        }
                        else if (m.Status == "Delivered")
                        {
                            <span>Delivered</span>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="card">
        <div class="card-text">
            No order history <a asp-action="Index" asp-controller="ProductCatalog">shop here</a>
        </div>
    </div>
}